[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter = +<../EspDos/>
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
lib_deps =
    FS
    LittleFS
